# .circleci/config.yml
version: 2.1

workflows:
  release-workflow:
    jobs:
      - test:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
            - test
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
  test-workflow:
    jobs:
      - test:
          filters:
            tags:
              ignore: /v[0-9]+\.[0-9]+\.[0-9]+/

jobs:
  release:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout

      - run: goreleaser

  test:
    docker:
      - image: cimg/go:1.13

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: Go lint
          command: "golint --set_exit_status ./..."

      - run:
          name: Go fmt
          command: "! go fmt ./... 2>&1 | read"

      - run:
          name: Go mod tidy
          command: "go mod tidy"

      - run:
          name: Run unit tests
          command: "mkdir -p test-results/; go test ./... -v -timeout 5m -coverprofile=test-results/coverage.out | tee test-results/tests.out"

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_artifacts:
          path: test-results/

      - store_test_results:
          path: test-results/