## slack specific configuration
slack:
  ## the token used to send messages to
  token: "my_token"
  ## the default channel if none are specified
  default_channel: "general"

client:
  ##  send messages to a http send2slack service, instead of using the token directly
  ## default: 127.0.0.1:4789
  ##  use string false to disable
  remote_url: "127.0.0.1:4789"
